<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-V8TS46C" failures="1" tests="3" name="mytest" time="0.042" errors="0" timestamp="3 Aug 2022 07:45:11 GMT">
  <testcase classname="day36.Test1" name="test1" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at day36.Test1.test1(Test1.java:11)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="day36.Test1" name="test2" time="0.002"/>
  <testcase classname="day36.Test1" name="test3" time="0.001"/>
</testsuite> <!-- mytest -->
